#!/usr/bin/env bash

if [[ -d "../src" && -d "../../qt" ]]; then
    if [[ ! -d "bin" ]]; then
        mkdir bin
    fi
    cd ../src
elif [[ -d "src" && -d "../qt" ]]; then
    if [[ ! -d "./env/bin" ]]; then
        mkdir env/bin
    fi
    cd src
else 
    echo "cannot build from here!"
fi

make clean
make qt

mv qt ../env/bin
mv qt.cm* ../env/bin
mv qt.o ../env/bin
